<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Property;

class PropertySeeder extends Seeder
{
    public function run(): void
    {
        Property::create([
            'title' => 'Light and modern apartment1',
            'description' => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.\n\nNam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum.",
            'type' => 'apartment',
            'status' => 'for rent',
            'property_status' => 'published',
            'is_paid' => true,
            'label' => 'hot',
            'price' => 4500,
            'second_price' => 500,
            'after_price' => 'month',
            'price_prefix' => '$',
            'bedrooms' => 4,
            'bathrooms' => 2,
            'garages' => 1,
            'garages_size' => '200 SqFt',
            'area_size' => 1200,
            'size_prefix' => 'Sq Ft',
            'land_area' => '2000',
            'land_area_size_postfix' => 'Sq Ft',
            'property_id' => 'HZ40',
            'energy_class' => 'A',
            'global_energy_performance_index' => '92.42 kWh / m2a',
            'renewable_energy_performance_index' => '21.12 kWh / m2a',
            'energy_performance_of_the_building' => 'something',
            'year_built' => 2016,
            'property_feature' => [
                'Air Conditioning',
                'Barbeque',
                'Dryer',
                'Gym',
                'Laundry',
                'Lawn',
                'Microwave',
                'Outdoor Shower',
                'Refrigerator',
                'Sauna',
                'Swimming Pool',
                'TV Cable',
                'Washer',
                'WiFi',
                'Window Coverings'
            ],
            'address' => '2436 SW 8th St',
            'country' => 'United States',
            'county_state' => 'Florida',
            'city' => 'Miami',
            'neighborhood' => 'West Flagger',
            'zip_postal_code' => '33140',
            'latitude' => 25.7650205,
            'longitude' => -80.2358097,
            'video_url' => '<iframe width="730" height="387" src="https://www.youtube.com/embed/cuGfG0J1aIw" frameborder="0" allowfullscreen></iframe>',
            'virtual_tour' => '<iframe width="853" height="480" src="https://my.matterport.com/show/?m=zEWsxhZpGba&play=1&qs=1" frameborder="0" allowfullscreen="allowfullscreen"></iframe>',
            'contact_information' => ["agent_data"],
            'private_note' => 'private not long',
            'user_id' => 8, // Assuming a default user ID; adjust as needed
            'is_featured' => true,
            'views' => 123,
            'unique_views' => 213,
        ]);

        // Additional Property 1
        Property::create([
            'title' => 'Modern Office Space in Downtown',
            'description' => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
            'type' => 'office',
            'status' => 'for rent',
            'property_status' => 'published',
            'is_paid' => true,
            'label' => 'available now',
            'price' => 5000,
            'second_price' => 2321,
            'after_price' => 'month',
            'price_prefix' => '$',
            'bedrooms' => 3,
            'bathrooms' => 3,
            'garages' => 2,
            'garages_size' => '400 SqFt',
            'area_size' => 2000,
            'size_prefix' => 'Sq Ft',
            'land_area' => '2500',
            'land_area_size_postfix' => 'Sq Ft',
            'property_id' => 'HZ41',
            'energy_class' => 'B',
            'global_energy_performance_index' => '85.50 kWh / m2a',
            'renewable_energy_performance_index' => '15.00 kWh / m2a',
            'energy_performance_of_the_building' => 'good',
            'year_built' => 2019,
            'property_feature' => [
                'Air Conditioning',
                'Barbeque',
                'Dryer',
                'Gym',
                'Laundry',
                'Lawn',
                'Microwave',
                'Outdoor Shower',
                'Refrigerator',
                'Sauna',
                'Swimming Pool',
                'TV Cable',
                'Washer',
                'WiFi',
                'Window Coverings'
            ],
            'address' => '100 Biscayne Blvd',
            'country' => 'United States',
            'county_state' => 'Florida',
            'city' => 'Miami',
            'neighborhood' => 'Downtown',
            'zip_postal_code' => '33132',
            'latitude' => 25.774,
            'longitude' => -80.193,
            'video_url' => '<iframe width="730" height="387" src="https://www.youtube.com/embed/cuGfG0J1aIw" frameborder="0" allowfullscreen></iframe>',
            'virtual_tour' => '<iframe width="853" height="480" src="https://my.matterport.com/show/?m=zEWsxhZpGba&play=1&qs=1" frameborder="0" allowfullscreen="allowfullscreen"></iframe>',
            'contact_information' => ["agent_data"],
            'private_note' => 'private note for this property',
            'user_id' => 8,
            'is_featured' => false,
            'views' => 150,
            'unique_views' => 120,
        ]);

        // Additional Property 2
        Property::create([
            'title' => 'Luxurious Home on Collins Ave',
            'description' => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
            'type' => 'home',
            'status' => 'for_sale',
            'property_status' => 'published',
            'is_paid' => true,
            'label' => 'new',
            'price' => 1200000,
            'second_price' => 3232,
            'after_price' => 'month',
            'price_prefix' => '$',
            'bedrooms' => 4,
            'bathrooms' => 3,
            'garages' => 2,
            'garages_size' => '300 SqFt',
            'area_size' => 2500,
            'size_prefix' => 'Sq Ft',
            'land_area' => '3000',
            'land_area_size_postfix' => 'Sq Ft',
            'property_id' => 'HZ42',
            'energy_class' => 'A',
            'global_energy_performance_index' => '90.00 kWh / m2a',
            'renewable_energy_performance_index' => '20.00 kWh / m2a',
            'energy_performance_of_the_building' => 'excellent',
            'year_built' => 2022,
            'property_feature' => [
                'Air Conditioning',
                'Barbeque',
                'Dryer',
                'Gym',
                'Laundry',
                'Lawn',
                'Microwave',
                'Outdoor Shower',
                'Refrigerator',
                'Sauna',
                'Swimming Pool',
                'TV Cable',
                'Washer',
                'WiFi',
                'Window Coverings'
            ],
            'address' => '4567 Collins Ave',
            'country' => 'United States',
            'county_state' => 'Florida',
            'city' => 'Miami Beach',
            'neighborhood' => 'Beachfront',
            'zip_postal_code' => '33140',
            'latitude' => 25.761,
            'longitude' => -80.191,
            'video_url' => '<iframe width="730" height="387" src="https://www.youtube.com/embed/cuGfG0J1aIw" frameborder="0" allowfullscreen></iframe>',
            'virtual_tour' => '<iframe width="853" height="480" src="https://my.matterport.com/show/?m=zEWsxhZpGba&play=1&qs=1" frameborder="0" allowfullscreen="allowfullscreen"></iframe>',
            'contact_information' => ["agent_data"],
            'private_note' => 'private note for this property',
            'user_id' => 8,
            'is_featured' => true,
            'views' => 200,
            'unique_views' => 180,
        ]);

        // Additional Property 3
        Property::create([
            'title' => 'Charming Villa on Coral Way',
            'description' => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
            'type' => 'villa',
            'status' => 'for rent',
            'property_status' => 'published',
            'is_paid' => true,
            'label' => 'hot deal',
            'price' => 6000,
            'second_price' => 563,
            'after_price' => 'month',
            'price_prefix' => '$',
            'bedrooms' => 5,
            'bathrooms' => 4,
            'garages' => 3,
            'garages_size' => '500 SqFt',
            'area_size' => 3500,
            'size_prefix' => 'Sq Ft',
            'land_area' => '4000',
            'land_area_size_postfix' => 'Sq Ft',
            'property_id' => 'HZ43',
            'energy_class' => 'B',
            'global_energy_performance_index' => '95.00 kWh / m2a',
            'renewable_energy_performance_index' => '25.00 kWh / m2a',
            'energy_performance_of_the_building' => 'good',
            'year_built' => 2015,
            'property_feature' => [
                'Air Conditioning',
                'Barbeque',
                'Dryer',
                'Gym',
                'Laundry',
                'Lawn',
                'Microwave',
                'Outdoor Shower',
                'Refrigerator',
                'Sauna',
                'Swimming Pool',
                'TV Cable',
                'Washer',
                'WiFi',
                'Window Coverings'
            ],
            'address' => '8901 Coral Way',
            'country' => 'United States',
            'county_state' => 'Florida',
            'city' => 'Miami',
            'neighborhood' => 'Coral Gables',
            'zip_postal_code' => '33165',
            'latitude' => 25.750,
            'longitude' => -80.240,
            'video_url' => '<iframe width="730" height="387" src="https://www.youtube.com/embed/cuGfG0J1aIw" frameborder="0" allowfullscreen></iframe>',
            'virtual_tour' => '<iframe width="853" height="480" src="https://my.matterport.com/show/?m=zEWsxhZpGba&play=1&qs=1" frameborder="0" allowfullscreen="allowfullscreen"></iframe>',
            'contact_information' => ["agent_data"],
            'private_note' => 'private note for this property',
            'user_id' => 8,
            'is_featured' => false,
            'views' => 300,
            'unique_views' => 250,
        ]);

        // Additional Property 4
        Property::create([
            'title' => 'Commercial Property on Flagler St',
            'description' => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
            'type' => 'commercial',
            'status' => 'for_sale',
            'property_status' => 'published',
            'is_paid' => true,
            'label' => 'sold',
            'price' => 800000,
            'second_price' => 0,
            'after_price' => 'month',
            'price_prefix' => '$',
            'bedrooms' => 3,
            'bathrooms' => 2,
            'garages' => 2,
            'garages_size' => '1231',
            'area_size' => 4000,
            'size_prefix' => 'Sq Ft',
            'land_area' => '4500',
            'land_area_size_postfix' => 'Sq Ft',
            'property_id' => 'HZ44',
            'energy_class' => 'C',
            'global_energy_performance_index' => '100.00 kWh / m2a',
            'renewable_energy_performance_index' => '30.00 kWh / m2a',
            'energy_performance_of_the_building' => 'average',
            'year_built' => 2010,
            'property_feature' => [
                'Air Conditioning',
                'Barbeque',
                'Dryer',
                'Gym',
                'Laundry',
                'Lawn',
                'Microwave',
                'Outdoor Shower',
                'Refrigerator',
                'Sauna',
                'Swimming Pool',
                'TV Cable',
                'Washer',
                'WiFi',
                'Window Coverings'
            ],
            'address' => '2345 Flagler St',
            'country' => 'United States',
            'county_state' => 'Florida',
            'city' => 'Miami',
            'neighborhood' => 'Little Havana',
            'zip_postal_code' => '33135',
            'latitude' => 25.772,
            'longitude' => -80.230,
            'video_url' => '<iframe width="730" height="387" src="https://www.youtube.com/embed/cuGfG0J1aIw" frameborder="0" allowfullscreen></iframe>',
            'virtual_tour' => '<iframe width="853" height="480" src="https://my.matterport.com/show/?m=zEWsxhZpGba&play=1&qs=1" frameborder="0" allowfullscreen="allowfullscreen"></iframe>',
            'contact_information' => ["agent_data"],
            'private_note' => 'private note for this property',
            'user_id' => 8,
            'is_featured' => true,
            'views' => 250,
            'unique_views' => 200,
        ]);

        // Additional Property 5
        Property::create([
            'title' => 'Residential Apartment in NW Miami',
            'description' => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
            'type' => 'residential',
            'status' => 'for rent',
            'property_status' => 'published',
            'is_paid' => true,
            'label' => 'rented',
            'price' => 3000,
            'second_price' => 322,
            'after_price' => 'month',
            'price_prefix' => '$',
            'bedrooms' => 3,
            'bathrooms' => 2,
            'garages' => 1,
            'garages_size' => '200 SqFt',
            'area_size' => 1500,
            'size_prefix' => 'Sq Ft',
            'land_area' => '1800',
            'land_area_size_postfix' => 'Sq Ft',
            'property_id' => 'HZ45',
            'energy_class' => 'A',
            'global_energy_performance_index' => '92.42 kWh / m2a',
            'renewable_energy_performance_index' => '21.12 kWh / m2a',
            'energy_performance_of_the_building' => 'something',
            'year_built' => 2017,
            'property_feature' => [
                'Air Conditioning',
                'Barbeque',
                'Dryer',
                'Gym',
                'Laundry',
                'Lawn',
                'Microwave',
                'Outdoor Shower',
                'Refrigerator',
                'Sauna',
                'Swimming Pool',
                'TV Cable',
                'Washer',
                'WiFi',
                'Window Coverings'
            ],
            'address' => '6789 NW 7th Ave',
            'country' => 'United States',
            'county_state' => 'Florida',
            'city' => 'Miami',
            'neighborhood' => 'Little Haiti',
            'zip_postal_code' => '33150',
            'latitude' => 25.780,
            'longitude' => -80.200,
            'video_url' => '<iframe width="730" height="387" src="https://www.youtube.com/embed/cuGfG0J1aIw" frameborder="0" allowfullscreen></iframe>',
            'virtual_tour' => '<iframe width="853" height="480" src="https://my.matterport.com/show/?m=zEWsxhZpGba&play=1&qs=1" frameborder="0" allowfullscreen="allowfullscreen"></iframe>',
            'contact_information' => ["agent_data"],
            'private_note' => 'private note for this property',
            'user_id' => 8,
            'is_featured' => true,
            'views' => 180,
            'unique_views' => 150,
        ]);

        // Additional Property 6
        Property::create([
            'title' => 'Spacious Studio in Brickell',
            'description' => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
            'type' => 'studio',
            'status' => 'for_sale',
            'property_status' => 'published',
            'is_paid' => true,
            'label' => 'new',
            'price' => 350000,
            'second_price' => 0,
            'after_price' => 'year',
            'price_prefix' => '$',
            'bedrooms' => 1,
            'bathrooms' => 1,
            'garages' => 1,
            'garages_size' => '100 SqFt',
            'area_size' => 800,
            'size_prefix' => 'Sq Ft',
            'land_area' => '1000',
            'land_area_size_postfix' => 'Sq Ft',
            'property_id' => 'HZ46',
            'energy_class' => 'A',
            'global_energy_performance_index' => '92.42 kWh / m2a',
            'renewable_energy_performance_index' => '21.12 kWh / m2a',
            'energy_performance_of_the_building' => 'something',
            'year_built' => 2023,
            'property_feature' => [
                'Air Conditioning',
                'Barbeque',
                'Dryer',
                'Gym',
                'Laundry',
                'Lawn',
                'Microwave',
                'Outdoor Shower',
                'Refrigerator',
                'Sauna',
                'Swimming Pool',
                'TV Cable',
                'Washer',
                'WiFi',
                'Window Coverings'
            ],
            'address' => '11213 Brickell Ave',
            'country' => 'United States',
            'county_state' => 'Florida',
            'city' => 'Miami',
            'neighborhood' => 'Brickell',
            'zip_postal_code' => '33131',
            'latitude' => 25.760,
            'longitude' => -80.190,
            'video_url' => '<iframe width="730" height="387" src="https://www.youtube.com/embed/cuGfG0J1aIw" frameborder="0" allowfullscreen></iframe>',
            'virtual_tour' => '<iframe width="853" height="480" src="https://my.matterport.com/show/?m=zEWsxhZpGba&play=1&qs=1" frameborder="0" allowfullscreen="allowfullscreen"></iframe>',
            'contact_information' => ["agent_data"],
            'private_note' => 'private note for this property',
            'user_id' => 8,
            'is_featured' => false,
            'views' => 220,
            'unique_views' => 190,
        ]);

        // Additional Property 7
        Property::create([
            'title' => 'Retail Shop on Lincoln Rd',
            'description' => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
            'type' => 'shop',
            'status' => 'for rent',
            'property_status' => 'published',
            'is_paid' => true,
            'label' => 'available now',
            'price' => 4000,
            'second_price' => 0,
            'after_price' => 'month',
            'price_prefix' => '$',
            'bedrooms' => 2,
            'bathrooms' => 1,
            'garages' => 1,
            'garages_size' => '300',
            'area_size' => 1000,
            'size_prefix' => 'Sq Ft',
            'land_area' => '1200',
            'land_area_size_postfix' => 'Sq Ft',
            'property_id' => 'HZ47',
            'energy_class' => 'B',
            'global_energy_performance_index' => '85.00 kWh / m2a',
            'renewable_energy_performance_index' => '15.00 kWh / m2a',
            'energy_performance_of_the_building' => 'good',
            'year_built' => 2021,
            'property_feature' => [
                'Air Conditioning',
                'Barbeque',
                'Dryer',
                'Gym',
                'Laundry',
                'Lawn',
                'Microwave',
                'Outdoor Shower',
                'Refrigerator',
                'Sauna',
                'Swimming Pool',
                'TV Cable',
                'Washer',
                'WiFi',
                'Window Coverings'
            ],
            'address' => '1415 Lincoln Rd',
            'country' => 'United States',
            'county_state' => 'Florida',
            'city' => 'Miami Beach',
            'neighborhood' => 'South Beach',
            'zip_postal_code' => '33139',
            'latitude' => 25.790,
            'longitude' => -80.140,
            'video_url' => '<iframe width="730" height="387" src="https://www.youtube.com/embed/cuGfG0J1aIw" frameborder="0" allowfullscreen></iframe>',
            'virtual_tour' => '<iframe width="853" height="480" src="https://my.matterport.com/show/?m=zEWsxhZpGba&play=1&qs=1" frameborder="0" allowfullscreen="allowfullscreen"></iframe>',
            'contact_information' => ["agent_data"],
            'private_note' => 'private note for this property',
            'user_id' => 8,
            'is_featured' => true,
            'views' => 350,
            'unique_views' => 300,
        ]);

        // Additional Property 8
        Property::create([
            'title' => 'Elegant Office in Coral Gables',
            'description' => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
            'type' => 'office',
            'status' => 'for_sale',
            'property_status' => 'published',
            'is_paid' => true,
            'label' => 'hot deal',
            'price' => 700000,
            'second_price' => 0,
            'after_price' => 'month',
            'price_prefix' => '$',
            'bedrooms' => 3,
            'bathrooms' => 2,
            'garages' => 2,
            'garages_size' => '300 SqFt',
            'area_size' => 1800,
            'size_prefix' => 'Sq Ft',
            'land_area' => '2000',
            'land_area_size_postfix' => 'Sq Ft',
            'property_id' => 'HZ48',
            'energy_class' => 'A',
            'global_energy_performance_index' => '92.42 kWh / m2a',
            'renewable_energy_performance_index' => '21.12 kWh / m2a',
            'energy_performance_of_the_building' => 'something',
            'year_built' => 2014,
            'property_feature' => [
                'Air Conditioning',
                'Barbeque',
                'Dryer',
                'Gym',
                'Laundry',
                'Lawn',
                'Microwave',
                'Outdoor Shower',
                'Refrigerator',
                'Sauna',
                'Swimming Pool',
                'TV Cable',
                'Washer',
                'WiFi',
                'Window Coverings'
            ],
            'address' => '2020 Ponce de Leon Blvd',
            'country' => 'United States',
            'county_state' => 'Florida',
            'city' => 'Coral Gables',
            'neighborhood' => 'Coral Gables',
            'zip_postal_code' => '33134',
            'latitude' => 25.755,
            'longitude' => -80.260,
            'video_url' => '<iframe width="730" height="387" src="https://www.youtube.com/embed/cuGfG0J1aIw" frameborder="0" allowfullscreen></iframe>',
            'virtual_tour' => '<iframe width="853" height="480" src="https://my.matterport.com/show/?m=zEWsxhZpGba&play=1&qs=1" frameborder="0" allowfullscreen="allowfullscreen"></iframe>',
            'contact_information' => ["agent_data"],
            'private_note' => 'private note for this property',
            'user_id' => 8,
            'is_featured' => true,
            'views' => 400,
            'unique_views' => 350,
        ]);

        // Additional Property 9
        Property::create([
            'title' => 'Cozy Home in Coconut Grove',
            'description' => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
            'type' => 'home',
            'status' => 'for rent',
            'property_status' => 'published',
            'is_paid' => true,
            'label' => 'new',
            'price' => 4500,
            'second_price' => 1221,
            'after_price' => 'month',
            'price_prefix' => '$',
            'bedrooms' => 3,
            'bathrooms' => 2,
            'garages' => 1,
            'garages_size' => '200 SqFt',
            'area_size' => 2000,
            'size_prefix' => 'Sq Ft',
            'land_area' => '2500',
            'land_area_size_postfix' => 'Sq Ft',
            'property_id' => 'HZ49',
            'energy_class' => 'A',
            'global_energy_performance_index' => '92.42 kWh / m2a',
            'renewable_energy_performance_index' => '21.12 kWh / m2a',
            'energy_performance_of_the_building' => 'something',
            'year_built' => 2016,
            'property_feature' => [
                'Air Conditioning',
                'Barbeque',
                'Dryer',
                'Gym',
                'Laundry',
                'Lawn',
                'Microwave',
                'Outdoor Shower',
                'Refrigerator',
                'Sauna',
                'Swimming Pool',
                'TV Cable',
                'Washer',
                'WiFi',
                'Window Coverings'
            ],
            'address' => '3030 SW 27th Ave',
            'country' => 'United States',
            'county_state' => 'Florida',
            'city' => 'Miami',
            'neighborhood' => 'Coconut Grove',
            'zip_postal_code' => '33133',
            'latitude' => 25.735,
            'longitude' => -80.240,
            'video_url' => '<iframe width="730" height="387" src="https://www.youtube.com/embed/cuGfG0J1aIw" frameborder="0" allowfullscreen></iframe>',
            'virtual_tour' => '<iframe width="853" height="480" src="https://my.matterport.com/show/?m=zEWsxhZpGba&play=1&qs=1" frameborder="0" allowfullscreen="allowfullscreen"></iframe>',
            'contact_information' => ["agent_data"],
            'private_note' => 'private note for this property',
            'user_id' => 8,
            'is_featured' => true,
            'views' => 280,
            'unique_views' => 240,
        ]);
    }
}
